### ISSUE TITLE
client crash when right clicking any pot with dirt

### ISSUE THREAD

**Issue by Drycask** [Darkhax-Minecraft/BotanyPots#3]
---- Minecraft Crash Report ----
// There are four lights!

Time: 12/14/19 2:01 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.darkhax.bookshelf.util.WorldUtils.getRecipes(WorldUtils.java:116) ~[?:4.4.71] {re:classloading}
	at net.darkhax.botanypots.BotanyPotHelper.getSoil(BotanyPotHelper.java:46) ~[?:1.0.5] {re:classloading}
	at net.darkhax.botanypots.block.tileentity.TileEntityBotanyPot.resetGrowthTime(TileEntityBotanyPot.java:177) ~[?:1.0.5] {re:classloading}
	at net.darkhax.botanypots.block.tileentity.TileEntityBotanyPot.setSoil(TileEntityBotanyPot.java:72) ~[?:1.0.5] {re:classloading}
	at net.darkhax.botanypots.block.BlockBotanyPot.func_220051_a(BlockBotanyPot.java:130) ~[?:1.0.5] {re:classloading}
	at net.minecraft.block.BlockState.func_215687_a(BlockState.java:395) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:281) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.func_217292_a(PlayerControllerOF.java:98) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1236) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,xf:fml:screenshotclipboard:coremodone,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1488) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,xf:fml:screenshotclipboard:coremodone,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1321) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,xf:fml:screenshotclipboard:coremodone,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:869) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,xf:fml:screenshotclipboard:coremodone,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,xf:fml:screenshotclipboard:coremodone,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.103.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$402/1687902353.call(Unknown Source) [forge-1.14.4-28.1.103.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.darkhax.bookshelf.util.WorldUtils.getRecipes(WorldUtils.java:116)
	at net.darkhax.botanypots.BotanyPotHelper.getSoil(BotanyPotHelper.java:46)
	at net.darkhax.botanypots.block.tileentity.TileEntityBotanyPot.resetGrowthTime(TileEntityBotanyPot.java:177)
	at net.darkhax.botanypots.block.tileentity.TileEntityBotanyPot.setSoil(TileEntityBotanyPot.java:72)
	at net.darkhax.botanypots.block.BlockBotanyPot.func_220051_a(BlockBotanyPot.java:130)
	at net.minecraft.block.BlockState.func_215687_a(BlockState.java:395)
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:281)
	at net.optifine.override.PlayerControllerOF.func_217292_a(PlayerControllerOF.java:98)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1236)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1488)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Waukonda'/41875, l='MpServer', x=-159.32, y=13.00, z=47.70]]
	Chunk stats: Client Chunk Cache: 529, 324
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-256,64,146), Chunk: (at 0,4,2 in -16,9; contains blocks -256,0,144 to -241,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1400431 game time, 1401204 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:574)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$402/1687902353.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2287485576 bytes (2181 MB) / 7317487616 bytes (6978 MB) up to 9544663040 bytes (9102 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10240m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.103.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.103.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.103.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.103.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.14.4_HD_U_F4.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.1.103.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.103
	FML Language Providers: 
		javafml@28.1
		minecraft@1
		kotori_scala@2.13.1
	Mod List: 
		tetra-1.14.4-1.0.7.jar Tetra {tetra@1.0.7 DONE}
		CyclopsCore-1.14.4-1.6.1.jar Cyclops Core {cyclopscore@1.6.1 DONE}
		justenoughbeacons-1.1.jar Just Enough Beacons {justenoughbeacons@1.1 DONE}
		autorun-1.14.4-1.0.5.jar Auto-Sprint {autorun@1.14.4-1.0.5 DONE}
		curiousshulkerboxes-FORGE-1.14.4-1.0.0.1.jar Curious Shulker Boxes {curiousshulkerboxes@FORGE-1.14.4-1.0.0.1 DONE}
		SilentMechanisms-1.14.4-0.6.9+42.jar Silent's Mechanisms {silents_mechanisms@0.6.9+42 DONE}
		modnametooltip_1.14.3-1.12.1.jar Mod Name Tooltip {modnametooltip@1.12.1 DONE}
		KleeSlabs_1.14.4-7.4.7.jar KleeSlabs {kleeslabs@7.4.7 DONE}
		findme-1.14.4-1.1.0.13.jar Find Me {findme@NONE DONE}
		Neat 1.5-19.jar Neat {neat@1.5-19 DONE}
		glassential-forge-1.14.4-1.1.1.jar Glassential {glassential@1.1.1 DONE}
		xnet-1.14-1.8.5-alpha.jar XNet {xnet@1.14-1.8.5-alpha DONE}
		XaerosWorldMap_1.5.2_Forge_1.14.4.jar Xaero's World Map {xaeroworldmap@1.5.2 DONE}
		CookingForBlockheads_1.14.4-7.4.1.jar Cooking for Blockheads {cookingforblockheads@7.4.1 DONE}
		Controlling-5.0.4.jar Controlling {controlling@5.0.4 DONE}
		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 DONE}
		globaldatapack-1.14.4-1.2.1.jar Dark Roleplay - Global Datapacks {globaldatapack@1.14.4-1.2 DONE}
		mightyarchitect-mc1.14.4_v0.5.jar The Mighty Architect {mightyarchitect@0.5 DONE}
		Fence Jumper-1.14.4-1.0.8.jar FenceJumper {fencejumper@version DONE}
		Bookshelf-1.14.4-4.4.71.jar Bookshelf {bookshelf@4.4.71 DONE}
		u_team_core-1.14.4-2.7.8.138.jar U Team Core {uteamcore@2.7.8.138 DONE}
		randompatches-1.14.4-1.19.1.1.jar RandomPatches {randompatches@1.14.4-1.19.1.1 DONE}
		buildinggadgets-3.1.1b.jar Building Gadgets {buildinggadgets@3.1.1b DONE}
		DarkUtilities-1.14.4-2.0.8.jar Dark Utilities {darkutils@2.0.8 DONE}
		Apotheosis-1.14.4-2.4.4.jar Apotheosis {apotheosis@2.4.4 DONE}
		Morpheus-1.14.4-4.2.44.jar Morpheus {morpheus@version DONE}
		FpsReducer-mc1.14.4-1.13.jar FPS Reducer {fpsreducer@mc1.14.4-1.13 DONE}
		JustEnoughResources-1.14.4-0.10.0.66.jar Just Enough Resources {jeresources@0.10.0.66 DONE}
		mysticallib-1.14.4-1.10.0.jar Mystical Lib {mysticallib@1.14.4-1.10.0 DONE}
		refinedstorage-1.7.1.jar Refined Storage {refinedstorage@1.7.1 DONE}
		mcw-bridges-1.0.2-mc1.14.4.jar Macaw's Bridges {mcwbridges@1.0.2 DONE}
		industrial-foregoing-1.14.4-2.1.0-69a4a14.jar Industrial Foregoing {industrialforegoing@2.1.0 DONE}
		dwmh-1.14.4-3.1.1.jar Dude! Where's my Horse? {dwmh@1.14.4-3.1.1 DONE}
		torchmaster-2.0.0-rc1.jar Torchmaster {torchmaster@2.0.0-rc1 DONE}
		cndtpd_1.14-1.0.jar Conduits Prevent Drowned {cndtpd@1.0 DONE}
		turf-1.14.4-1.0.0.jar Turf {turf@1.0.0 DONE}
		CommonCapabilities-1.14.4-2.4.4.jar CommonCapabilities {commoncapabilities@2.4.4 DONE}
		Geolosys-1.14.4-4.0.10.jar Geolosys {geolosys@4.0.10 DONE}
		BiomesOPlenty-1.14.4-9.0.0.259-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.259 DONE}
		practicaltools-1.14.4-1.4.jar Practical Tools {practicaltools@1.14.4-1.4 DONE}
		LetSleepingDogsLie-1.14.4-1.1.0.jar Let Sleeping Dogs Lie {dogslie@1.1.0 DONE}
		cycp_1.14-1.0.jar Cycle Paintings {cycp@1.0 DONE}
		simplefarming-1.14.4-1.2.2.jar Simple Farming {simplefarming@1.14.4-1.2.2 DONE}
		LLOverlayReloaded-1.2.4-mc1.14.4.jar Light Level Overlay Reloaded {llor@1.2.4-mc1.14.4 DONE}
		fishingreal-1.1.jar Fishing Real {fishingreal@1.1 DONE}
		portality-1.14.4-2.0.4-b0b3467.jar Portality {portality@2.0.4 DONE}
		curios-FORGE-1.14.4-1.0.6.jar Curios API {curios@FORGE-1.14.4-1.0.6 DONE}
		corail_woodcutter-1.0.6-1.14.4.jar Corail Woodcutter {corail_woodcutter@1.0.6 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		TorchBandolier-1.14.4-1.3.2+7.jar Torch Bandolier {torchbandolier@1.3.2+7 DONE}
		OreExcavation-1.6.145.jar Ore Excavation {oreexcavation@1.6.145 DONE}
		angelring-1.14.4-1.1.0-pre1.jar Angel Ring {angelring@1.1.0-pre1 DONE}
		tombstone-4.1.7-1.14.4.jar Corail Tombstone {tombstone@4.1.7 DONE}
		hidden-levers.jar Hidden Levers {hiddenlevers@1.0 DONE}
		curiouselytra-FORGE-1.14.4-1.0.jar Curious Elytra {curiouselytra@FORGE-1.14.4-1.0 DONE}
		UpgradeModifiers-1.14.4-1.0.2.jar UpgradeModifiers {upgrademodifiers@1.0.2 DONE}
		globalxp-1.14.4-v1.4.10.jar Global XP {globalxp@v1.4.10 DONE}
		BetterBurning-1.14.4-1.0.1.jar BetterBurning {betterburning@1.0.1 DONE}
		CobbleForDays-1.0.2.jar Cobble For Days {cobblefordays@NONE DONE}
		StevesFactoryManager-1.14.4-3.0.0-alpha21.jar Steve's Factory Manager {sfm@1.14.4-3.0.0-alpha DONE}
		DangerousStoneCutter-1.14.4-1.2.0.jar Dangerous Stone Cutter {dangerousstonecutter@1.2.0 DONE}
		BetterAdvancements-1.14.4-0.1.0.93.jar Better Advancements {betteradvancements@0.1.0.93 DONE}
		inventorysorter-1.14.4-16.2.0.jar Simple Inventory Sorter {inventorysorter@16.2.0 DONE}
		Cucumber-1.14.4-2.0.5.jar Cucumber Library {cucumber@2.0.5 DONE}
		InventorySpam-1.14.4-1.2.3.jar Inventory Spam {inventoryspam@version DONE}
		EquipmentTooltips-1.14.4-1.3.2+10.jar Equipment Tooltips {equipmenttooltips@1.3.2+10 DONE}
		creeperfix-1.14.4-1.3.jar CreeperFix {creeperfix@1.3 DONE}
		craftingstation-2.1.3b.jar Crafting Station {craftingstation@2.1.3b DONE}
		bountifulbaubles-1.14.4-0.0.2.jar Bountiful Baubles {bountifulbaubles@NONE DONE}
		BambooBlocksV1.2.8.jar Bamboo Blocks {bambooblocks@1.2.8 DONE}
		PersistentBits-1.14.4-2.0.2.jar Persistent Bits {persistentbits@2.0.2 DONE}
		jei-1.14.4-6.0.0.26.jar Just Enough Items {jei@6.0.0.26 DONE}
		EverlastingAbilities-1.14.4-1.6.0.jar EverlastingAbilities {everlastingabilities@1.6.0 DONE}
		AttributeFix-1.14.4-3.0.3.jar AttributeFix {attributefix@3.0.3 DONE}
		cosmeticbeds-FORGE-1.14.4-2.0.0.1.jar Cosmetic Beds {cosmeticbeds@FORGE-1.14.4-2.0.0.1 DONE}
		seals-1.14.4-1.0.2.jar Seals {seals@1.0.2 DONE}
		caelus-FORGE-1.14.4-1.0.1.1.jar Caelus API {caelus@FORGE-1.14.4-1.0.1.1 DONE}
		colytra-FORGE-1.14.4-2.1.0.jar Colytra {colytra@FORGE-1.14.4-2.1.0 DONE}
		extraboats-1.1.2-1.14.4.jar Extra Boats {extraboats@1.1.2 DONE}
		ensorcellation-1.14.4-0.2.0b.jar Ensorcellation {ensorcellation@0.2.0b DONE}
		create-mc1.14.4_v0.1.1a.jar Create {create@0.1.1a DONE}
		mgui-1.14.4-1.0.1.jar mgui {mgui@1.0.1 DONE}
		comforts-FORGE-1.14.4-2.0-beta4.jar Comforts {comforts@FORGE-1.14.4-2.0-beta4 DONE}
		SimpleStorageNetwork-1.14.4-0.1.0.jar Simple Storage Network {storagenetwork@1.14.4-0.1.0 DONE}
		gardentools-1.14.4-1.0.0.jar Garden Tools {gardentools@1.14.4-1.0.0 DONE}
		cursedearth-1.4a.jar Cursed Earth {cursedearth@1.4a DONE}
		BotanyPots-1.14.4-1.0.5.jar BotanyPots {botanypots@1.0.5 DONE}
		curioofundying-FORGE-1.14.4-2.0.jar Curio of Undying {curioofundying@FORGE-1.14.4-2.0 DONE}
		FarmingForBlockheads_1.14.4-5.2.3.jar Farming for Blockheads {farmingforblockheads@5.2.3 DONE}
		cofh_core-1.14.4-0.2.0b.jar CoFH Core {cofh_core@0.2.0b DONE}
		demagnetize-1.14.4-1.2.1.jar Demagnetize {demagnetize@1.14.4-1.2.1 DONE}
		alib-1.14.4-7.jar A Lib {alib@1.14.4-7 DONE}
		mcjtylib-1.14-3.5.15-alpha.jar McJtyLib {mcjtylib@1.14-3.5.15-alpha DONE}
		rftoolsbase-1.14-0.0.11-alpha.jar RFToolsBase {rftoolsbase@1.14-0.0.11-alpha DONE}
		rftoolsstorage-1.14-0.0.6-alpha.jar RFToolsStorage {rftoolsstorage@1.14-0.0.6-alpha DONE}
		ClickMachine-1.14.4-2.1.2.jar Click Machine {clickmachine@2.1.2 DONE}
		voyage-1.0.0.jar Voyage {voyage@1.0.0 DONE}
		ToastControl-1.14.4-2.2.0.jar Toast Control {toastcontrol@2.2.0 DONE}
		PackingTape-1.14.4-0.9.0.jar Packing Tape {packingtape@0.9.0 DONE}
		traverse-1.14.4-2.0.3.jar Traverse {traverse@1.14.4-2.0.3 DONE}
		mininggadgets-1.2.3.jar Mining Gadgets {mininggadgets@1.2.3 DONE}
		CraftTweaker-1.14.4-5.0.1.149.jar CraftTweaker {crafttweaker@5.0.1.149 DONE}
		rftoolspower-1.14-1.2.11-alpha.jar RFToolsPower {rftoolspower@1.14-1.2.11-alpha DONE}
		mysticalworld-1.14.4-1.6.12.jar Mystical World {mysticalworld@1.14.4-1.6.12 DONE}
		campfiretorches-1.14.4-1.0.3.jar Campfire Torches {campfiretorches@1.14.4-1.0.3 DONE}
		forge-1.14.4-28.1.103-universal.jar Forge {forge@28.1.103 DONE}
		QuickLeafDecay-MC1.14.4-1.2.5.jar Quick Leaf Decay {quickleafdecay@1.2.5 DONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		CraftingTweaks_1.14.4-10.1.4.jar Crafting Tweaks {craftingtweaks@10.1.4 DONE}
		forge-1.14.4-28.1.103-client.jar Minecraft {minecraft@1.14.4 DONE}
		rftoolsutility-1.14-1.2.12-alpha.jar RFToolsUtility {rftoolsutility@1.14-1.2.12-alpha DONE}
		Flopper-1.14.4-1.0.5.jar Flopper {flopper@1.0.5 DONE}
		EnchantmentDescriptions-1.14.4-1.3.8.jar EnchantmentDescriptions {enchdesc@1.3.8 DONE}
		theoneprobe-1.14-1.4.37.jar The One Probe {theoneprobe@NONE DONE}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 DONE}
		MouseTweaks-2.12-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.12 DONE}
		watercan-1.14.4-2.1.0.jar Watercan {watercan@1.14.4-2.1.0 DONE}
		titanium-1.14.4-2.2.9.jar Titanium {titanium@2.2.9 DONE}
		SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 DONE}
		bluepower-1.14.4-0.3.161-alpha-universal.jar Blue Power {bluepower@0.3.161-alpha DONE}
		RingOfGrowth-1.14.4-1.0.19.jar Ring of Growth {ring_of_growth@1.0.19 DONE}
		CapabilityProxy-1.14.4-2.1.5.jar CapabilityProxy {capabilityproxy@2.1.5 DONE}
		Ding-1.14.4-1.1.0.jar Ding {ding@1.1.0 DONE}
		creatureslovebeacons-FORGE-1.14.4-2.0.jar Creatures Love Beacons {creatureslovebeacons@FORGE-1.14.4-2.0 DONE}
		LargeFluidTank-14.8.9.jar FluidTank {fluidtank@14.8.9 DONE}
		rftoolsbuilder-1.14-1.2.10-alpha.jar RFToolsBuilder {rftoolsbuilder@1.14-1.2.10-alpha DONE}
		dimdungeons-1.02-forge-1.14.4.jar Dimensional Dungeons {dimdungeons@1.14.4-1.02 DONE}
		foamdome-2.0.2.jar Foam Dome {foamdome@2.0.2 DONE}
		Quark-r2.0-201.jar Quark {quark@r2.0-201 DONE}
		Xaeros_Minimap_1.19.2_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@1.19.2 DONE}
		FTBUtilitiesBackups-2.0.0.11.jar FTB Utilities: Backups {ftbbackups@2.0.0.11 DONE}
		FastWorkbench-1.14.4-2.1.4.jar FastWorkbench {fastbench@2.1.4 DONE}
		StorageDrawers-1.14.4-6.0.5.jar Storage Drawers {storagedrawers@1.14.4-6.0.3 DONE}
		simplytea-2.0.3.jar Simply Tea {simplytea@2.0.3 DONE}
		structurize-0.10.201-ALPHA.jar Structurize {structurize@0.10.201-ALPHA DONE}
		ScreenshotToClipboard-1.14.4-1.0.3.jar Screenshot to Clipboard {screenshotclipboard@1.14.4-1.0.3 DONE}
		minecolonies-0.10.586-ALPHA-universal.jar Minecolonies {minecolonies@0.10.586-ALPHA DONE}
		FastFurnace-1.14.4-2.2.4.jar FastFurnace {fastfurnace@2.2.4 DONE}
		World-Stripper-1.7.2-1.14.4.jar World Stripper {worldstripper@version DONE}
		AppleSkin-mc1.14.4-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		engineersdecor-1.14.4-1.0.17-b1.jar Engineer's Decor {engineersdecor@1.0.17-b1 DONE}
		solcarrot-1.14.4-1.9.3.jar Spice of Life: Carrot Edition {solcarrot@1.14.4-1.9.3 DONE}
		RingOfAttraction-1.14.4-1.0.19.jar Ring of Attraction {ring_of_attraction@1.0.19 DONE}
		nps_1.14-2.1.jar Nether Portal Spread {nps@2.1 DONE}
		modular-routers-1.14.4-5.1.2-7.jar Modular Routers {modularrouters@1.14.4-5.1.2-7 DONE}
		easyelytrato_1.14-1.1.jar Easy Elytra Takeoff {easyelytrato@1.1 DONE}
		smallernp_1.14-1.1.jar Smaller Nether Portals {smallernp@1.1 DONE}
		Aquaculture-1.14.4-2.0.2.jar Aquaculture 2 {aquaculture@1.14.4-2.0.2 DONE}
		FriendlyFire-1.14.4-3.0.2.jar FriendlyFire {friendlyfire@3.0.2 DONE}
		mysticalwildlife-1.14.4-1.3.3.jar Mystical Wildlife {mysticalwildlife@1.3.3 DONE}
		refinedstorageaddons-0.5.jar Refined Storage Addons {refinedstorageaddons@0.5 DONE}
		CosmeticArmorReworked-1.14.4-v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.14.4-v1a DONE}
		packmode-1.14.4-2.0.0.jar Pack Mode {packmode@1.14.4-2.0.0 DONE}
		draw_bridge-1.14.4-1.2.3.13.jar Draw Bridge {drawbridge@1.2.3.13 DONE}
		DefaultOptions_1.14.4-10.2.6.jar Default Options {defaultoptions@10.2.6 DONE}
	Launched Version: forge-28.1.103
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.41, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	OptiFine Version: OptiFine_1.14.4_HD_U_F4
	OptiFine Build: 20191025-153543
	Render Distance Chunks: 12
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 441.41
	OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by Darkhax** [comment]
Thanks for the report, this is fixed in the next update.
