### ISSUE TITLE
[1.16.5] [Mystical Block] [net.darkhax.botanypots.crop.CropInfo

### ISSUE THREAD

**Issue by IntenseLeveLing** [Darkhax-Minecraft/BotanyPots#356]
### After restarting and spawning in the blocks they still don't work, tried crafting new one and still cant get into it.

```
[26Dec2023 15:39:05.468] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.ClassCastException: net.darkhax.botanypots.crop.CropInfo cannot be cast to net.minecraft.item.crafting.AbstractCookingRecipe
	at net.minecraft.tileentity.AbstractFurnaceTileEntity.func_235642_a_(AbstractFurnaceTileEntity.java:452) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_392]
	at net.minecraft.tileentity.AbstractFurnaceTileEntity.func_235640_a_(AbstractFurnaceTileEntity.java:450) ~[?:?]
	at net.minecraft.block.AbstractFurnaceBlock.func_196243_a(SourceFile:72) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196947_b(AbstractBlock.java:616) ~[?:?]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:267) ~[?:?]
	at net.minecraft.world.World.func_241211_a_(World.java:199) ~[?:?]
	at net.minecraft.world.World.func_180501_a(World.java:176) ~[?:?]
	at net.minecraftforge.common.extensions.IForgeBlock.removedByPlayer(IForgeBlock.java:214) ~[forge:?]
	at net.minecraftforge.common.extensions.IForgeBlockState.removedByPlayer(IForgeBlockState.java:157) ~[forge:?]
	at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:271) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:254) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:220) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:190) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:929) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392]
[26Dec2023 15:39:05.518] [Server thread/WARN] [net.minecraft.tileentity.TileEntity/]: Block entity invalid: minecraft:furnace @ BlockPos{x=8, y=82, z=-7}
[26Dec2023 15:39:11.068] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.ClassCastException: net.darkhax.botanypots.crop.CropInfo cannot be cast to net.minecraft.item.crafting.AbstractCookingRecipe
	at net.minecraft.tileentity.AbstractFurnaceTileEntity.func_235642_a_(AbstractFurnaceTileEntity.java:452) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_392]
	at net.minecraft.tileentity.AbstractFurnaceTileEntity.func_235640_a_(AbstractFurnaceTileEntity.java:450) ~[?:?]
	at net.minecraft.block.AbstractFurnaceBlock.func_196243_a(SourceFile:72) ~[?:?]
	at com.blakebr0.mysticalagriculture.block.EssenceFurnaceBlock.func_196243_a(EssenceFurnaceBlock.java:66) ~[mysticalagriculture:4.2.6]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196947_b(AbstractBlock.java:616) ~[?:?]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:267) ~[?:?]
	at net.minecraft.world.World.func_241211_a_(World.java:199) ~[?:?]
	at net.minecraft.world.World.func_180501_a(World.java:176) ~[?:?]
	at net.minecraftforge.common.extensions.IForgeBlock.removedByPlayer(IForgeBlock.java:214) ~[forge:?]
	at net.minecraftforge.common.extensions.IForgeBlockState.removedByPlayer(IForgeBlockState.java:157) ~[forge:?]
	at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:271) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:254) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:220) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:190) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:929) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392]
[26Dec2023 15:39:11.116] [Server thread/WARN] [net.minecraft.tileentity.TileEntity/]: Block entity invalid: mysticalagriculture:inferium_furnace @ BlockPos{x=8, y=82, z=-6}
```

### **[AFTER RESTART] this also gets spat when leaving dimension/coming back to overworld etc**

```
[16:13:46] [Netty Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument@253a42f2 (class cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument) - will not be sent to client!
[16:13:46] [Netty Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument@62c72e37 (class cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument) - will not be sent to client!
[16:13:52] [Netty Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument@253a42f2 (class cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument) - will not be sent to client!
[16:13:52] [Netty Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument@62c72e37 (class cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument) - will not be sent to client!
```

### Complete log file. time frame of error around 15:35~

[2023-12-26-1.log](https://github.com/Darkhax-Minecraft/BotanyPots/files/13773725/2023-12-26-1.log)

**Comment by IntenseLeveLing** [comment]
and now all of a sudden after a 3rd restart it works -_-... solved i guess????still curious to see what was the problem though thanks

**Comment by Darkhax** [comment]
Hello, I just finished looking through the info you provided and it looks like your game has an ID conflict between two recipes. The log doesn't show which recipe is specifically at fault, but it's sometimes being loaded as a furnace recipe and other times a botany pots recipe. If this happens again it would be a good idea to look into the nbt of the furnace to see what recipe is causing the issue and then fix that in the modpack.
