### ISSUE TITLE
Botany Pots 1.16.1-3.0.2 causes the forge loader to crash

### ISSUE THREAD

**Issue by starrysurprise** [Darkhax-Minecraft/BotanyPots#62]
Thank you for making this mod! I'm using the most current versions of Forge and Java. I verified that Botany Pots was the problematic file by removing recent mods one at a time until the loader finally worked, then I added each back one by one. I don't know how to read crash reports very well, so if I'm wrong about Botany Pots being the problematic mod here I'm sorry! Thank you for taking the time to read this :)

Here is the crash report:

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 7/21/20 6:39 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraft.client.renderer.color.ItemColors.func_199877_a(ItemColors.java:97) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.github.commoble.bagofyurting.client.ClientEvents.registerItemColors(ClientEvents.java:19) ~[?:1.16.1-1.0.0.1] {re:classloading}
	at com.github.commoble.bagofyurting.client.ClientEvents$$Lambda$3671/1237024192.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2786/221402392.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:32.0] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$4119/1274308620.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:219) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onItemColorsInit(ForgeHooksClient.java:170) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:86) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:450) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.71.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$431/1939869193.call(Unknown Source) [forge-1.16.1-32.0.71.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.color.ItemColors.func_199877_a(ItemColors.java:97)
	at com.github.commoble.bagofyurting.client.ClientEvents.registerItemColors(ClientEvents.java:19)
	at com.github.commoble.bagofyurting.client.ClientEvents$$Lambda$3671/1237024192.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2786/221402392.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260)
	at net.minecraftforge.fml.ModLoader$$Lambda$4119/1274308620.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:219)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260)
	at net.minecraftforge.client.ForgeHooksClient.onItemColorsInit(ForgeHooksClient.java:170)
	at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:86)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:450)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$431/1939869193.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 806374152 bytes (769 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.71.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.71.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.71.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.71.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.16.1_HD_U_G2_pre5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.71.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.71
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		JustMoreCakes-1.0_MC1.16.1_beta.jar Just More Cake! {jmc@1.0 CREATE_REGISTRIES}
		doubledoors_1.16-2.1.jar Double Doors {doubledoors@2.1 CREATE_REGISTRIES}
		randomloot-2.1.2.jar Random Loot Mod {randomloot@2.1.2 CREATE_REGISTRIES}
		torchslabmod-1.16.1_v1.6.16.jar Torch Slab Mod {torchslabmod@1.6.16 CREATE_REGISTRIES}
		mining-helmet-1.16.1-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 CREATE_REGISTRIES}
		ItemFavorites-[1.16.1]-1.0.0.jar Item Favorites {itemfav@1.0.0 CREATE_REGISTRIES}
		bagofyurting-1.16.1-1.0.0.1.jar Bag of Yurting {bagofyurting@1.16.1-1.0.0.1 CREATE_REGISTRIES}
		jei-1.16.1-7.0.0.6.jar Just Enough Items {jei@7.0.0.6 CREATE_REGISTRIES}
		mooshroomtweaks_1.16-1.1.jar Mooshroom Tweaks {mooshroomtweaks@1.1 CREATE_REGISTRIES}
		Abnormals-Core-1.16.1-v2.0.0.jar Abnormals Core {abnormals_core@2.0.0 CREATE_REGISTRIES}
		Buzzier-Bees-1.16.1-2.0.0.jar Buzzier Bees {buzzier_bees@2.0.0 CREATE_REGISTRIES}
		Berry-Good-1.16.1-3.0.0.jar Berry Good {berry_good@3.0.0 CREATE_REGISTRIES}
		Enhanced-Mushrooms-1.16.1-v2.0.3.jar Enhanced Mushrooms {enhanced_mushrooms@2.0.0 CREATE_REGISTRIES}
		KiwiBirds+1.2+1.16.1.jar Kiwi Birds {kiwibirds@1.2 1.16.1 CREATE_REGISTRIES}
		modnametooltip_1.16.1-1.14.0.jar Mod Name Tooltip {modnametooltip@1.14.0 CREATE_REGISTRIES}
		pitg-1.16.1-1.3.0.jar Pane In The Glass {pitg@1.16.1-1.3.0 CREATE_REGISTRIES}
		Extra-Boats-1.16.1-1.4.0.jar Extra Boats {extraboats@1.4.0 CREATE_REGISTRIES}
		bundleditems-mc1.16.1-1.3.1.jar Bundled Items {bundleditems@1.3.1 CREATE_REGISTRIES}
		Waystones_1.16.1-7.0.2.jar Waystones {waystones@7.0.2 CREATE_REGISTRIES}
		GravelMiner_1.16.1-10.0.0.jar GravelMiner {gravelminer@10.0.0 CREATE_REGISTRIES}
		JasonsDisenchantment_1.0.0_Forge_1.16.1.jar Anvil Disenchantments {disenchant@1.0.0 CREATE_REGISTRIES}
		NaturesCompass-1.16.1-1.8.5.jar Nature's Compass {naturescompass@1.16.1-1.8.5 CREATE_REGISTRIES}
		netheritehorsearmor-1.0.jar Netherite Horse Armor Mod {netheritehorsearmor@1.0 CREATE_REGISTRIES}
		decorative_blocks-7a.jar Decorative Blocks {decorative_blocks@7a CREATE_REGISTRIES}
		potionsmaster-0.1.8-1.16.1-32.0.57.jar Potions Master {potionsmaster@0.1.8 CREATE_REGISTRIES}
		Bookshelf-1.16.1-6.1.11.jar Bookshelf {bookshelf@6.1.11 CREATE_REGISTRIES}
		BedBenefits-1.16.1-1.0.1.jar BedBenefits {bedbenefits@1.0.1 CREATE_REGISTRIES}
		BotanyPots-1.16.1-3.0.2.jar BotanyPots {botanypots@3.0.2 ERROR}
		Bamboo-Blocks-1.16.1-2.0.0.jar Bamboo Blocks {bamboo_blocks@NONE CREATE_REGISTRIES}
		nhacampfire_1.16-2.3.jar No Hostiles Around Campfire {nhacampfire@2.3 CREATE_REGISTRIES}
		bedspreads-FORGE-1.16.1-4.0.jar Bedspreads {bedspreads@FORGE-1.16.1-4.0 CREATE_REGISTRIES}
		travellersboots-1.16.1-1.4.0.jar Traveller's Boots {travellersboots@1.4.0 CREATE_REGISTRIES}
		carpetstairsmod-1.16.1_v1.4.6.jar Carpet Stairs Mod {carpetstairsmod@1.4.6 CREATE_REGISTRIES}
		fixedanvilrepaircost_1.16-1.1.jar Fixed Anvil Repair Cost {fixedanvilrepaircost@1.1 CREATE_REGISTRIES}
		dismountentity_1.16-1.2.jar Dismount Entity {dismountentity@1.2 CREATE_REGISTRIES}
		infinityworkswithallarrows-1.0.jar Infinity works with all arrows {infinityworkswithallarrows@1.0 CREATE_REGISTRIES}
		vanillaexperience-1.16.1-0.1.9.jar Vanilla Experience {vanillaexperience@0.1.9 CREATE_REGISTRIES}
		ExpOreMod-1.16.1-1.0.jar Exp Ore Block {exp_ore@1.0 CREATE_REGISTRIES}
		endercompass-3.0.jar Ender Compass {endercompass@3.0 CREATE_REGISTRIES}
		moveminecarts_1.16-1.3.jar Move Minecarts {moveminecarts@1.3 CREATE_REGISTRIES}
		campfiretorches-1.16.1-1.0.2.jar Campfire Torches {campfiretorches@1.16.1-1.0.2 CREATE_REGISTRIES}
		forge-1.16.1-32.0.71-universal.jar Forge {forge@32.0.71 CREATE_REGISTRIES}
		PassthroughSigns-1.16.1-2.3.4.jar Passthrough Signs {passthroughsigns@1.16.1-2.3.4 CREATE_REGISTRIES}
		conduitsprdrowned_1.16-1.1.jar Conduits Prevent Drowned {conduitsprdrowned@1.1 CREATE_REGISTRIES}
		JEIEnchantmentInfo-1.16.1-1.1.0.jar JEI Enchantment Info {jeienchantmentinfo@1.16.1-1.0.0 CREATE_REGISTRIES}
		SimpleDivingGear-5.0.0+mc+1.16.1.jar Simple Diving Gear {simpledivegear@5.0.0 mc 1.16.1 CREATE_REGISTRIES}
		forge-1.16.1-32.0.71-client.jar Minecraft {minecraft@1.16.1 CREATE_REGISTRIES}
		mcw-bridges-1.0.4-mc1.16.1.jar Macaw's Bridges {mcwbridges@1.0.4 CREATE_REGISTRIES}
		GentleFawn-1.0.3-MC1.16.1.jar Gentle Fawn {gentlefawn@1.0.3 CREATE_REGISTRIES}
		nccreepers_1.16-1.2.jar Naturally Charged Creepers {nccreepers@1.2 CREATE_REGISTRIES}
		morevanillalib-1.16.1-1.2.8.jar MoreVanillaLib {morevanillalib@1.2.8 CREATE_REGISTRIES}
		concreteconversion-1.16.1-4.1.0.0.jar Concrete Conversion {concreteconversion@1.16.1-4.1.0.0 CREATE_REGISTRIES}
		nutritiousmilk_1.16-1.2.jar Nutritious Milk {nutritiousmilk@1.2 CREATE_REGISTRIES}
		LetSleepingDogsLie-1.16.1-1.1.1.jar Let Sleeping Dogs Lie {dogslie@1.1.1 CREATE_REGISTRIES}
		rare-ice-0.2.1.jar Rare Ice {rare-ice@version CREATE_REGISTRIES}
		moveboats_1.16-1.2.jar Move Boats {moveboats@1.2 CREATE_REGISTRIES}
		goprone-1.16.x-1.0.0.jar GoProne {goprone@1.16.x-1.0.0 CREATE_REGISTRIES}
		Mainly+Additions+1.16.1.jar Mainly Additions {mam@1.0 CREATE_REGISTRIES}
		curios-FORGE-1.16.1-3.0.jar Curios API {curios@FORGE-1.16.1-3.0 CREATE_REGISTRIES}
		Savage-and-Ravage-1.16.1-2.0.0.jar Savage & Ravage {savageandravage@2.0.0 CREATE_REGISTRIES}
		rndbmflowers_1.16-1.2.jar Random Bone Meal Flowers {rndbmflowers@1.2 CREATE_REGISTRIES}
		gravestone-1.16.1-1.0.3.jar Gravestone Mod {gravestone@1.16.1-1.0.3 CREATE_REGISTRIES}
		collective-1.16.1-1.35.jar Collective {collective@1.35 CREATE_REGISTRIES}
		OverpoweredMending-1.16.1-2.0.0+11.jar Overpowered Mending {overpowered_mending@2.0.0+11 CREATE_REGISTRIES}
		cyclepaintings_1.16-1.3.jar Cycle Paintings {cyclepaintings@1.3 CREATE_REGISTRIES}
		camera-1.16.1-1.0.4.jar Camera Mod {camera@1.16.1-1.0.4 CREATE_REGISTRIES}
		bunnyboots-1.1.1.jar Bunny Boots {bunnyboots@1.1.1 CREATE_REGISTRIES}
		polymorph-FORGE-1.16.1-0.10.jar Polymorph {polymorph@FORGE-1.16.1-0.10 CREATE_REGISTRIES}
		StorageDrawers-1.16.1-8.0.0.jar Storage Drawers {storagedrawers@1.16.1-8.0.0 CREATE_REGISTRIES}
		sit-1.16.1-v1.3.jar Sit {sit@v1.3 CREATE_REGISTRIES}
		DoubleSlabs-1.16-3.1.2.jar Double Slabs {doubleslabs@3.1.2 CREATE_REGISTRIES}
		betbeacpl_1.16-1.1.jar Better Beacon Placement {betbeacpl@1.1 CREATE_REGISTRIES}
		vanillahammers-1.16.1-2.1.1.jar Vanilla Hammers {vanillahammers@2.1.1 CREATE_REGISTRIES}
		lottaterracotta-1.16.1-1.3.1.jar Lotta Terracotta {lottaterracotta@1.16.1-1.3.1 CREATE_REGISTRIES}
		lanterncolors-1.16.1-2.0.0.jar Lantern Colors {lanterncolors@1.16.1-2.0.0 CREATE_REGISTRIES}
		buildersaddition-20200721a.jar Builders Crafts & Addition {buildersaddition@20200721a CREATE_REGISTRIES}
		AppleSkin-mc1.16.1-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 CREATE_REGISTRIES}
		nametagtweaks_1.16-1.1.jar Name Tag Tweaks {nametagtweaks@1.1 CREATE_REGISTRIES}
		biomeinfo-1.16.1-v1.2.5.jar BiomeInfo {biomeinfo@v1.2.5 CREATE_REGISTRIES}
		SakuraRosea-1.4.4-MC1.16.1.jar Sakura Rosea {sakurarosea@1.4.4 CREATE_REGISTRIES}
		easyelytrato_1.16-1.3.jar Easy Elytra Takeoff {easyelytrato@1.3 CREATE_REGISTRIES}
		Incubation-1.16.1-1.1.0.jar Incubation {incubation@1.1.0 CREATE_REGISTRIES}
		PrettyBeaches_1.16.1-5.0.0.jar Pretty Beaches {prettybeaches@5.0.0 CREATE_REGISTRIES}
		healingcf_1.16-2.3.jar Healing Campfire {healingcf@2.3 CREATE_REGISTRIES}
		xptome-1.16.1-v1.1.6.jar XP Tome {xpbook@v1.1.6 CREATE_REGISTRIES}
		cullparticles-1.0.jar Cull Particles {cullparticles@1.0 CREATE_REGISTRIES}
		bigbuckets-1.1.1.jar BigBuckets {bigbuckets@1.1.1 CREATE_REGISTRIES}
	Launched Version: 1.16.1-forge-32.0.71
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 26.20.100.7870, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz
	OptiFine Version: OptiFine_1.16.1_HD_U_G2_pre5
	OptiFine Build: 20200719-015630
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.27 Extreme-VL.zip
	OpenGlVersion: 4.6.0 - Build 26.20.100.7870
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by Darkhax** [comment]
Please try updating Botany Pots to 3.0.4

**Comment by starrysurprise** [comment]
It works! I’m sorry about that, I must have downloaded the wrong file.
