### ISSUE TITLE
1.16.1 Crash on Plant Botania Flower

### ISSUE THREAD

**Issue by kaffeekirsche** [Darkhax-Minecraft/BotanyPots#68]
Server Crashes when planting Botania Flower.

Minecraft: 1.16.1
Forge: 32.0.106
Mod: BotanyPots-1.16.1-3.0.5.jar

`[11Aug2020 17:28:48.055] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:856) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:286) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NoSuchMethodError: net.darkhax.botanypots.block.tileentity.TileEntityBotanyPot.func_145833_n()D
	at net.darkhax.botanypots.block.tileentity.TileEntityBotanyPot.onCropHarvest(TileEntityBotanyPot.java:347) ~[?:3.0.5]
	at net.darkhax.botanypots.block.tileentity.TileEntityBotanyPot.attemptAutoHarvest(TileEntityBotanyPot.java:336) ~[?:3.0.5]
	at net.darkhax.botanypots.block.tileentity.TileEntityBotanyPot.onTileTick(TileEntityBotanyPot.java:263) ~[?:3.0.5]
	at net.darkhax.bookshelf.block.tileentity.TileEntityBasicTickable.func_73660_a(TileEntityBasicTickable.java:27) ~[?:6.3.20]
	at net.minecraft.world.World.func_217391_K(World.java:533) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:364) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852) ~[?:?]
	... 5 more`

**Comment by Darkhax** [comment]
Hello, this was fixed a few days ago. Please update to 3.0.6.

**Comment by pandory-network** [comment]
Twitch launcher have only showing me release versions. Now in have found the alpha version. Thx for help
