### ISSUE TITLE
Rendering Block Entity crash with version 1.16.1-3.0.6

### ISSUE THREAD

**Issue by JossMM** [Darkhax-Minecraft/BotanyPots#69]
Game crashed when I tried to place dirt in a pink hopper pot. World is currently unrecoverable due to this crash. I'm using the latest version of BotanyPots available on CurseForge.

BotanyPots version: 1.16.1-3.0.6
Java version: 1.8.0.712
Forge version: 32.0.75

From crash report:

Description: Rendering Block Entity

java.lang.NoSuchMethodError: net.darkhax.bookshelf.util.RenderUtils.findRenderType(Lnet/minecraft/block/BlockState;)Lnet/minecraft/client/renderer/RenderType;
	at net.darkhax.botanypots.block.tileentity.RendererBotanyPot.renderBlock(RendererBotanyPot.java:132) ~[?:3.0.6] {re:classloading,pl:runtimedistcleaner:A}
	at net.darkhax.botanypots.block.tileentity.RendererBotanyPot.render(RendererBotanyPot.java:79) ~[?:3.0.6] {re:classloading,pl:runtimedistcleaner:A}
	at net.darkhax.botanypots.block.tileentity.RendererBotanyPot.func_225616_a_(RendererBotanyPot.java:34) ~[?:3.0.6] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:101) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:85) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher$$Lambda$15501/1682113887.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:118) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:84) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1017) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:601) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:422) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:951) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.75.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$472/22958662.call(Unknown Source) [forge-1.16.1-32.0.75.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.darkhax.botanypots.block.tileentity.RendererBotanyPot.renderBlock(RendererBotanyPot.java:132)
	at net.darkhax.botanypots.block.tileentity.RendererBotanyPot.render(RendererBotanyPot.java:79)
	at net.darkhax.botanypots.block.tileentity.RendererBotanyPot.func_225616_a_(RendererBotanyPot.java:34)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:101)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:85)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher$$Lambda$15501/1682113887.run(Unknown Source)

-- Block Entity Details --
Details:
	Name: botanypots:botany_pot // net.darkhax.botanypots.block.tileentity.TileEntityBotanyPot
	Block: Block{botanypots:hopper_pink_botany_pot}[powered=false]
	Block location: World: (-183,70,-550), Chunk: (at 9,4,10 in -12,-35; contains blocks -192,0,-560 to -177,255,-545), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Block: Block{botanypots:hopper_pink_botany_pot}[powered=false]
	Block location: World: (-183,70,-550), Chunk: (at 9,4,10 in -12,-35; contains blocks -192,0,-560 to -177,255,-545), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:118)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:84)
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1017)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:601)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Villyriot'/31, l='ClientLevel', x=-182.28, y=69.00, z=-548.75]]
	Chunk stats: Client Chunk Cache: 841, 533
	Level dimension: minecraft:overworld
	Level spawn location: World: (128,68,-224), Chunk: (at 0,4,0 in 8,-14; contains blocks 128,0,-224 to 143,255,-209), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1030110 game time, 205991 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:445)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:598)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$472/22958662.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

**Comment by Darkhax** [comment]
Hello, please update to the latest version of Bookshelf. https://www.curseforge.com/minecraft/mc-mods/bookshelf/files/3027445
