### ISSUE TITLE
Client crashes when putting a soil into a pot (probably invalid dependency version)

### ISSUE THREAD

**Issue by TomaszewskiPatryk** [Darkhax-Minecraft/BotanyPots#70]
When you try putting a soil intro a botany pot, the client will crash with the following message:
```
net.minecraft.crash.ReportedException: Rendering Block Entity
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:192) ~[?:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:99) ~[?:?]
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1775) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1014) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:691) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:951) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[client-1.16.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.1-32.0.106.jar:32.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?]
Caused by: java.lang.NoSuchMethodError: net.darkhax.bookshelf.util.RenderUtils.findRenderType(Lnet/minecraft/block/BlockState;)Lnet/minecraft/client/renderer/RenderType;
	at net.darkhax.botanypots.block.tileentity.RendererBotanyPot.renderBlock(RendererBotanyPot.java:154) ~[?:3.0.6]
	at net.darkhax.botanypots.block.tileentity.RendererBotanyPot.render(RendererBotanyPot.java:84) ~[?:3.0.6]
	at net.darkhax.botanypots.block.tileentity.RendererBotanyPot.func_225616_a_(RendererBotanyPot.java:34) ~[?:3.0.6]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:126) ~[?:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:101) ~[?:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:185) ~[?:?]
```
What's more, that soil will be put in place, so the game will crash after each attempt to load the world, making the save unplayable.

I'm pretty sure it's just an invalid bookshelf version used in BotanyPots' dependency check, as updating bookshelf from `6.3.16` to `6.3.20` seemed to resolve the issue.

**Comment by Darkhax** [comment]
Yes, this is an issue of not having the right bookshelf version installed.
