### ISSUE TITLE
TheOneProbe support doesn't work in SMP

### ISSUE THREAD

**Issue by jeremiahwinsley** [Darkhax-Minecraft/BotanyPots#84]
Mod versions:
Bookshelf-1.16.3-8.4.14.jar
BotanyPots-1.16.3-5.0.4.jar
theoneprobe-1.16-3.0.4-beta.jar

When viewing a Botany Pot with soil in it on SMP, One Probe shows `Error: botanypots:top_support`. 
The same setup on SSP shows soil and seed data correctly.

**Comment by Darkhax** [comment]
Could you send some client/server logs to help me further understand this issue?

**Comment by jeremiahwinsley** [comment]
server logs: [debug.log](https://gist.github.com/jeremiahwinsley/ef978deb0e27b7aad854c73fa49ecf56)

```
java.lang.NoSuchMethodError: net.minecraft.block.Block.func_235333_g_()Lnet/minecraft/util/text/IFormattableTextComponent;
	at net.darkhax.botanypots.soil.SoilInfo.getName(SoilInfo.java:95) ~[?:5.0.4]
	at net.darkhax.botanypots.addons.top.TOPPlugin.addPotInfo(TOPPlugin.java:61) ~[?:5.0.4]
	at net.darkhax.botanypots.addons.top.TOPPlugin.addProbeInfo(TOPPlugin.java:52) ~[?:5.0.4]
	at mcjty.theoneprobe.network.PacketGetInfo.getProbeInfo(PacketGetInfo.java:137) ~[?:1.16-3.0.4-beta]
	at mcjty.theoneprobe.network.PacketGetInfo.lambda$handle$0(PacketGetInfo.java:100) ~[?:1.16-3.0.4-beta]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?]
	at mcjty.theoneprobe.network.PacketGetInfo.handle(PacketGetInfo.java:97) ~[?:1.16-3.0.4-beta]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_242]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:76) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_242]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:76) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1326) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:729) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:156) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:712) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:706) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:692) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
``

**Comment by Darkhax** [comment]
Thanks for the report, this should be fixed now. Some fancy blocks may cause issues if used as crops/soils however I will be trying to get a fix for this in Forge.
